# Generated by Django 4.1.7 on 2023-03-15 16:17

import autoslug.fields
from django.db import migrations
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=products.models.set_slugify, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', slugify=products.models.set_slugify, verbose_name='slug'),
        ),
    ]
